services:
  - type: web
    name: mcp-server
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render/java 